### ISSUE TITLE
Console error only when using Spring

### ISSUE THREAD

**Issue by jasonperrone** [mattbrictson/airbrussh#133]
I have a Capistrano task that does this:

```
        execute :sudo, "touch /tmp/hello"
```

I execute with cap stage utils:my_task

If I don't use the Spring Rails application reloader, no problem. If I do use it, I get:
```
from /home/jason/.rvm/gems/ruby-2.7.3@rails61/gems/airbrussh-1.4.0/lib/airbrussh/console.rb:27:in `print_line'
/home/jason/.rvm/gems/ruby-2.7.3@rails61/gems/airbrussh-1.4.0/lib/airbrussh/console.rb:65:in `console_width': undefined method `winsize' for nil:NilClass (NoMethodError)
```

Apparently IO.console is null when I use the Spring preloader.

**Comment by jasonperrone** [comment]
Resolved the problem by putting set :format_options, truncate: false in deploy.rb. See this thread https://github.com/capistrano/capistrano/issues/1999
