### ISSUE TITLE
Uninitialized constant Airbrussh::SimpleDelegator

### ISSUE THREAD

**Issue by micbou** [mattbrictson/airbrussh#25]
### Configuration
Windows 7 64 bits
```
$ ruby --version
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
```
```
$ bundler list
Gems included by the bundle:
  * airbrussh (0.5.0)
  * breakpoint (2.5.0)
  * bundler (1.10.3)
  * capistrano (3.4.0)
  * chunky_png (1.3.4)
  * colorize (0.7.7)
  * compass (1.0.3)
  * compass-core (1.0.3)
  * compass-import-once (1.0.5)
  * ffi (1.9.8)
  * highline (1.7.2)
  * i18n (0.7.0)
  * multi_json (1.11.1)
  * net-scp (1.2.1)
  * net-ssh (2.9.2)
  * normalize-scss (3.0.2)
  * rainbow (2.0.0)
  * rake (10.4.2)
  * rb-fsevent (0.9.5)
  * rb-inotify (0.9.5)
  * sass (3.4.15)
  * sassy-maps (0.4.0)
  * scss-lint (0.38.0)
  * sshkit (1.7.1)
  * susy (2.2.5)
```

### Issue

I get the following error when executing the command `cap staging deploy --trace`:
```
cap aborted!
NameError: uninitialized constant Airbrussh::SimpleDelegator
C:/Ruby193/lib/ruby/gems/1.9.1/gems/airbrussh-0.5.0/lib/airbrussh/command_formatter.rb:7:in `<module:Airbrussh>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/airbrussh-0.5.0/lib/airbrussh/command_formatter.rb:5:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/airbrussh-0.5.0/lib/airbrussh/formatter.rb:2:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/airbrussh-0.5.0/lib/airbrussh.rb:2:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/airbrussh-0.5.0/lib/airbrussh/capistrano.rb:1:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
C:/Users/micbou/www/scaffolder/Capfile:16:in `<top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
C:/Ruby193/bin/cap:23:in `load'
C:/Ruby193/bin/cap:23:in `<main>'
```
It was working fine with the 0.4.1 version.

**Comment by binaryape** [comment]
Same for me too, with Ruby 2.1.2p95.

**Comment by mattbrictson** [comment]
Yikes! I'll issue a fix very soon.

**Comment by mattbrictson** [comment]
Fixed in a0c6dd2 and released to rubygems as 0.5.1. Sorry for the trouble!

**Comment by micbou** [comment]
Thanks for the quick fix.

**Comment by binaryape** [comment]
That was quick! I've updated and it seems fine - cheers!
